### ISSUE TITLE
Heroku Deploy Failed

### ISSUE THREAD

**Issue by 4nat** [vkaelin/YouTogether#15]
-----> Installing node-v12.16.2-linux-x64
-----> Detecting rake tasks
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/fog-core-2.2.0/lib/fog/core/service.rb:244:in `validate_options'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/fog-core-2.2.0/lib/fog/core/service.rb:268:in `handle_settings'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/fog-core-2.2.0/lib/fog/core/service.rb:98:in `new'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/fog-core-2.2.0/lib/fog/core/services_mixin.rb:29:in `new'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/carrierwave-1.1.0/lib/carrierwave/uploader/configuration.rb:124:in `eager_load_fog'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/carrierwave-1.1.0/lib/carrierwave/uploader/configuration.rb:137:in `fog_credentials='
       /tmp/build_57550d27_/config/initializers/carrierwave.rb:3:in `block in <top (required)>'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/carrierwave-1.1.0/lib/carrierwave/uploader/configuration.rb:159:in `configure'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/carrierwave-1.1.0/lib/carrierwave.rb:14:in `configure'
       /tmp/build_57550d27_/config/initializers/carrierwave.rb:1:in `<top (required)>'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:286:in `load'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:286:in `block in load'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:286:in `load'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/engine.rb:655:in `block in load_config_initializer'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:168:in `instrument'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/engine.rb:654:in `load_config_initializer'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/engine.rb:611:in `each'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/engine.rb:611:in `block in <class:Engine>'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `run'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/initializable.rb:59:in `block in run_initializers'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/initializable.rb:48:in `each'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/initializable.rb:48:in `tsort_each_child'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/initializable.rb:58:in `run_initializers'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/application.rb:353:in `initialize!'
       /tmp/build_57550d27_/config/environment.rb:5:in `<top (required)>'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/application.rb:329:in `require'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/application.rb:329:in `require_environment!'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/application.rb:445:in `block in run_tasks_blocks'
       /tmp/build_57550d27_/vendor/bundle/ruby/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

**Comment by vkaelin** [comment]
Hi!

If I remember correctly, deploying this website is not so easy on Heroku.
The website is using AWS S3 to store the users' avatars so you need to provide the key to your AWS bucket.

Here is the list of my Heroku config vars: 
![image](https://user-images.githubusercontent.com/33511688/90251705-804ba080-de3e-11ea-8d13-d4c3bf635ad6.png)

I've also followed [this article](https://blog.heroku.com/real_time_rails_implementing_websockets_in_rails_5_with_action_cable) to learn how to deploy a Rails app with Action Cable features (real time stuff).

Hope it will help you!

**Comment by 4nat** [comment]
**I am grateful for your quick response to my question I have an amazon aws account but what if the user's profile photo remains as default? so it would be better not to allow the user to make changes**

**Comment by 4nat** [comment]
**I mean, how can I deploy in the easiest and shortest way, I would be glad if you could help me. By the way, I examine your projects with pleasure. They are all very nice.**

**Comment by vkaelin** [comment]
I'm sorry but I've not used Rails/this project for 2 years so I'm not so sure about the changes needed to do that.

Here are some ideas:

- Remove the `mount_uploader` in the [user Model](https://github.com/vkaelin/YouTogether/blob/master/app/models/user.rb)
- Add a [default value](https://stackoverflow.com/questions/6167994/assigning-default-value-while-creating-migration-file) to the avatar string [in the migration](https://github.com/vkaelin/YouTogether/blob/master/db/migrate/20180619131657_add_avatar_to_user.rb) for example

Not really sure it will be enough to make it work though...

**Comment by 4nat** [comment]
It's a good project, but I don't know the ruby ​​language so I don't understand it. I wish it was done with node.js, but it's better. I tried all the methods but still could not deploy. The problem seems to be in gemfile and gemfile.lock. [article](https://blog.heroku.com/real_time_rails_implementing_websockets_in_rails_5_with_action_cable) 
I studied but did not understand very much. 
Could you tell me how you deployed in heroku with examples via email or any communication options. if you are available. You don't know how much I want this project. :smile:

**Comment by vkaelin** [comment]
Add me on Discord, Kalane#4147 but I'm not sure I will be able to help you.

**Comment by vkaelin** [comment]
Closing this one as we have managed to deploy it while chatting on Discord.
